#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BLUE=\\e[34m
GREEN=\\e[32m
NC=\\e[0m

echo ""
echo -e "${BLUE}Running pre-commit hook...${NC}"

npm run linter

echo ""
echo -e "${GREEN}inting completed ${NC}"
echo ""


