#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ""
echo -e "${BLUE}Running pre-commit hook...${NC}"


echo "Running pre-commit hook..." >&2

npm run linter

echo ""
echo -e "\e[32m Linting completed \e[0m"
echo ""


